### ISSUE TITLE
Update Library 

### ISSUE THREAD

**Issue by jousmo** [FrankHilhorst/node4progress#2]
They plan to update this library, I have tried to make it work for NodeJS version 10 and AppServer 11.X and Java 1.8

**Comment by FrankHilhorst** [comment]
What do you mean by "they plan to update this library"?.
I suspect that to make it work for Appserver 11 the java open client proxy needs to be regenerated.

**Comment by jousmo** [comment]
I'm interested in using your library.

With what operating system ?.

Which version of OE do you suggest (AppServer) ?.

JAVA version ?.

NodeJS version ?.

I think your documentation has some errors

const node4progress = require("node4progressHttp")(conf);
or
const node4progress = require("node4progress")(conf);

I would like you could help me answering the questions.

**Comment by FrankHilhorst** [comment]
Hi Jose,I did a test yesterday using node4progress using java 1.8 and OpenEdge 11.6.After I recompiled the code in OpenEdge 11.6 it worked fine.The base code that needs to be recompiled is in node_modules/node4progress/4GlCode/BaseCode.The code for the examples that needs to be recompiled is in node_modules/node4progress/4GlCode/examples.Also node4progress uses an embedded servlet engine that runs on port 8085.That port has to be accessible.I recommend that you set up an Appserver against the sports database and try the examples first.Beware that both the node_modules/node4progress/4GlCode/BaseCode and the node_modules/node4progress/4GlCode directories need to be in your propath.Let me know how you how you make out with this. Frank HilhorstPresidentProgressive Consulting IncDirect  772.418.8456Cell     561.843.2839Frank@ProgressiveConsultingInc.comwww.ProgressiveConsultingInc.com


-------- Original Message --------
Subject: Re: [FrankHilhorst/node4progress] Update Library (#2)

**Comment by jousmo** [comment]
Hi Frank

Excuse my English, I'm from Mexico

I want to understand that you use Windows and there you install OE 11.6, JAVA 1.8, NodeJS is this correct?

what version of nodejs do you use?

I have my next Stack

My Laptop :
OS: OSX
NodeJS Version 8.11.3
Java Version 1.8.0_152-b16

Unix Server
OS: AIX 7.2
OpenEdge (AppServer) 11.6

My intention is to communicate to the appserver from my local computer.

I'll do tests with what you just told me about the compiled

I thank you very much for your support

**Comment by FrankHilhorst** [comment]
Hi Jose,I am using:OE 1.6Java 1.8node 8.11Are you deploying your appserver on AIX?In that case the progress code included in node4progress must be deployed on AIX.It must be compiled on AIX as well.You can use the following code to test your appserver outside of node.In essence this is what node executes on the appserver.define var hServer as handle no-undo.def var handler as char no-undo init "Examples/CustomerHandler.p".def var iInputPars as longchar no-undo.def var oOutputPars as longchar no-undo.def var oDatasetJson as longchar no-undo.def var  oErrMsg as char no-undo.assign iInputPars = 'NumCustomersToPull=5'.create server hServer.hServer:connect("-DirectConnect -H localhost -S 3092").message hServer:connected() skip        search("NodeJsDispatch.r") skipview-as alert-box.run  NodeJsDispatch.r on hServer (     input handler,     input iInputPars,     input false,     output oOutputPars,     output oDatasetJson,     output oErrMsg).     message string(oDatasetJson) view-as alert-box.     hServer:disconnect().delete object hserver.assign hServer = ?.Frank HilhorstPresidentProgressive Consulting IncDirect  772.418.8456Cell     561.843.2839Frank@ProgressiveConsultingInc.comwww.ProgressiveConsultingInc.com


-------- Original Message --------
Subject: Re: [FrankHilhorst/node4progress] Update Library  (#2)

**Comment by jousmo** [comment]
Hi Frank.

I appreciate your time, yesterday I could do the tests and finally I could connect to the AppServer

I'm excited, now I'm working on the implementations. 

Thank you very much

Best regards

Jose Uscanga
